version: '3.8'

services:
  python-app:
    build: .
    container_name: python-app-arheanja
    ports:
      - "8000:8000"
    volumes:
      - app-data:/app/data
      - app-logs:/app/logs
      - ./src:/app/src:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    user: "1001:1001"

volumes:
  app-data:
    driver: local
  app-logs:
    driver: local